# Generated by Django 4.2.6 on 2023-10-30 10:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='defaults/default_model_image.png', upload_to='uploads/')),
                ('description', models.TextField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp of creation')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='modelestroisD.modele')),
                ('tags', models.ManyToManyField(blank=True, to='modelestroisD.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('version_number', models.CharField(default='1.0', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, upload_to='files/')),
                ('tags', models.ManyToManyField(blank=True, to='modelestroisD.tag')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='modelestroisD.variante')),
            ],
        ),
        migrations.AddField(
            model_name='modele',
            name='tags',
            field=models.ManyToManyField(blank=True, to='modelestroisD.tag'),
        ),
    ]
