# Generated by Django 4.2.6 on 2023-11-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelestroisD', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
